TRAIN:
  train_batch_size: 32
  lr: 0.0003

  valid_batch_size: 8

  image_size: [224,224]

  min_epochs: 20
  max_epochs: 200
  patience: 30
  text_length: 24

  device: 1

  model_save_path: ./save_model_mosmed_teacher
  model_save_filename: medseg
  best_model_path: ./save_model_mosmed_teacher/medseg.ckpt

  wrapper: Teacher

MODEL:
  bert_type: microsoft/BiomedVLP-CXR-BERT-specialized
  vision_type: facebook/convnext-tiny-224
  project_dim: 768
  model: languided

DATA:
  data: MosMedPlus
  train_csv_path: ./data/MosMedData+/prompt/train.csv
  train_root_path: ./data/MosMedData+/Train

  val_csv_path: ./data/MosMedData+/prompt/val.csv
  val_root_path: ./data/MosMedData+/Val

  test_csv_path: ./data/MosMedData+/prompt/test.csv
  test_root_path: ./data/MosMedData+/Test